name: Publish Python Package to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-python:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Create setup.py for backend package
        run: |
          cd backend
          cat > setup.py << EOF
          from setuptools import setup, find_packages

          with open("README.md", "r", encoding="utf-8") as fh:
              long_description = fh.read()

          setup(
              name="bazarmonitoring-backend",
              version="${{ github.ref_name }}",
              author="FROWNINGdev",
              author_email="dendigiden676@gmail.com",
              description="Backend API for BazarMonitoring - System for monitoring bazaars in Uzbekistan",
              long_description=long_description,
              long_description_content_type="text/markdown",
              url="https://github.com/FROWNINGdev/bazarmonitoring",
              packages=find_packages(),
              classifiers=[
                  "Development Status :: 4 - Beta",
                  "Intended Audience :: Developers",
                  "License :: OSI Approved :: MIT License",
                  "Operating System :: OS Independent",
                  "Programming Language :: Python :: 3",
                  "Programming Language :: Python :: 3.11",
              ],
              python_requires=">=3.11",
              install_requires=[
                  "flask>=2.3.0",
                  "flask-cors>=4.0.0",
                  "flask-sqlalchemy>=3.0.0",
                  "flask-migrate>=4.0.0",
                  "flask-restx>=1.2.0",
                  "requests>=2.31.0",
              ],
          )
          EOF
      
      - name: Build package
        run: |
          cd backend
          python -m build
      
      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd backend
          python -m twine upload --repository-url https://upload.pkg.github.com/FROWNINGdev/bazarmonitoring dist/*

